### ISSUE TITLE
Stoped working on 30.12.23 ? -> Solved with HA 2024.1.0b4

### ISSUE THREAD

**Issue by andreasbuff** [Hassassistant/openai_response#18]
Hello, I had this integration running for month.. now, on 30.12.23 it stopped working?  Probably, because of HA_2024.1.0bx  Beta-Release?

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 10:53:41 (1 occurrences)
Last logged: 10:53:41

Error setting up entry OpenAI Conversation for openai_conversation
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/openai_conversation/__init__.py", line 118, in async_setup_entry
    client = openai.AsyncOpenAI(api_key=entry.data[CONF_API_KEY])
             ^^^^^^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'AsyncOpenAI'

**Comment by andreasbuff** [comment]
Solved with Update of HA 2024.1.0b4 

- it is running now again. Thanks
